language: python
python:
  - 3.5
  - 3.6

before_install:
  - pip install --upgrade setuptools pip
install:
  - pip install --pre -r test-requirements.txt -e .
script:
  - pytest -v --cov=sudospawner sudospawner/tests

after_success:
  - codecov
