name: Test

# Trigger the workflow's on all PRs but only on pushed tags or commits to
# main/master branch to avoid PRs developed in a GitHub fork's dedicated branch
# to trigger.
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        include:
          - python-version: "3.9"
            pip-install-spec: "jupyterhub==4.*"
          - python-version: "3.11"
            pip-install-spec: "jupyterhub==5.*"
          - python-version: "3.13"
            pip-install-spec: "jupyterhub"
          - python-version: "3.x"
            pip-install-spec: "--pre jupyterhub"

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install ${{ matrix.pip-install-spec }}
          pip install -e ".[test]"

      - name: Run pytest
        run: |
          if [[ "${{ matrix.python }}" == "3.12" ]]; then
              # TODO: there is some issue with Python 3.12 and coverage that
              #       causes a test suite failure
              pytest
          else
              pytest --cov=sudospawner
          fi

      - uses: codecov/codecov-action@v5
