name: Test

on:
  pull_request:
    paths-ignore:
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags: ["**"]
  schedule:
    # At 05:00 on Monday - https://crontab.guru
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        include:
          - python-version: "3.9"
            pip-install-spec: "jupyterhub==4.*"
          - python-version: "3.11"
            pip-install-spec: "jupyterhub==5.*"
          - python-version: "3.13"
            pip-install-spec: "jupyterhub"
          - python-version: "3.x"
            pip-install-spec: "--pre jupyterhub"

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install ${{ matrix.pip-install-spec }}
          pip install -e ".[test]"

      - name: Run pytest
        run: |
          if [[ "${{ matrix.python }}" == "3.12" ]]; then
              # TODO: there is some issue with Python 3.12 and coverage that
              #       causes a test suite failure
              pytest
          else
              pytest --cov=sudospawner
          fi

      - uses: codecov/codecov-action@v5
