name: Test

# Trigger the workflow's on all PRs but only on pushed tags or commits to
# main/master branch to avoid PRs developed in a GitHub fork's dedicated branch
# to trigger.
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.x"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --pre -e ".[test]"

      - name: Run pytest
        run: |
          if [[ "${{ matrix.python }}" == "3.12" ]]; then
              # TODO: there is some issue with Python 3.12 and coverage that
              #       causes a test suite failure
              pytest
          else
              pytest --cov=sudospawner
          fi

      - uses: codecov/codecov-action@v5
