name: Test

# Trigger the workflow's on all PRs but only on pushed tags or commits to
# main/master branch to avoid PRs developed in a GitHub fork's dedicated branch
# to trigger.
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      # NOTE: actions/setup-python@v5 make use of a cache within the GitHub base
      #       environment and setup in a fraction of a second.
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --pre -r test-requirements.txt -e .
      - name: Run pytest
        run: |
          pytest -v --color=yes --cov=sudospawner sudospawner/tests
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
      - name: Submit codecov report
        uses: codecov/codecov-action@v4
